function getRandomGreeting() {
  var greetings = [
    "bee bee boo boo - the murphy",
    "How many sides does a circle have?",
    "You can read btw",
    "haahahahahhaahahahahahhahahahaahahhah - milner",
    "Redbull gives you wings...",
    "Since 2020!",
    "As seen on TV!",
    "doot doot",
    "drippy like ive!",
    "Made in China!",
    "Made by 3kh0!",
    "Press the little spinny thing on your keyboard",
    "Reading your search history...",
    "im funky",
    "time to get smarter and work harder not smarter",
    "why do people bite their ice cream, its horrifying",
    "#Relatable",
    "Fortnite is a creation no one could create",
    "You got games on your phone?",
    "Powered by hamsters!",
    "*insert monkeys blowing stuff up*",
    "Got to go fast!",
    "My iPad passcode is 1 btw",
    "Sponsered by RAID SHADOW LEGENDS!",
    "Sponsored by Honey!",
    "Sponsored by China Government!",
    "donate all your money to me so i can buy pokemon packs",
    "You is a bozo",
    "Powered by 0.9Gigs of RAM!",
    "Powered by 1MB of RAM!",
    "I'm Slim Shady, yes, I'm the real Shady!",
    "You're a real jerk!",
    "w h a t",
    "3kh0.net is here!",
    "what the dog doin?",
    "I'm gonna pop some tags",
    "henry busick my goat",
    "thx stackoverflow!",
    "are you a gaemer?",
    "It is time to get funky!",
    "releasing the epstein files...",
    "Don't ask questions if you can't handle the answers!",
    "If you are using Opera GX, you need some help.",
    "thank you sullivan",
    "shoutout to henry busick",
    "Shoutout to The Vietnamese Goverment!",
    "Woo! /g/",
    "https://www.youtube.com/watch?v=QkygslFH3kU",
    "youtube.com/@3kh0",
    "Please stop posting furry images.",
    "triple k the goat (kyle kyle kyle sahur)",
    "bottem text",
    "grand 26",
    "No fun allowed",
    "jackson bounds fell asleep in 3rd period",
    "i do love buying birth certificates from the black market! - Shaymin",
    "'If you are trash go play Fortnite you loser' - Sun Tzu, Art of war",
    "I was taking my whale on a walk when I realized my Dodge was leaking electricity so I called the FBI to get me some pizza but instead they raided my house I am talking from Pluto aa humans halp me",
    "i wanted free vbucks :(",
    "Avocados \ud83e\udd51 from Mexico \ud83c\uddf2\ud83c\uddfd",
    "reload for another message",
    "i voted for kanye",
    "He stomped on his fruit loops and thus became a cereal killer.",
    "Techonoblade never dies!",
    "And just to think I knew him before he was famous",
    "Trust me, I did not copy Minecraft with this",
    "Is there such a thing as minecraft on a school chromebook?",
    "That proves you are unusual",
    "What's my IP adress?",
    "This is the 5th time this week, and it's only Monday",
    "You bum",
    "i love roblox roblox is life",
    "Toss the Turtle is pretty fun",
    "Mission failed, we will get them next time",
    "NUKE INCOMING!",
    "I spent too much time making these",
    "hello from the murph",
    "miguel is a chromebook kid",
    "go do your homework",
    "gilliam is tall",
    "If your reading this your teacher is watching you",
    "aint no way he just said that",
    "I made miguel stop asking me to update ngon",
    "lorem ipsum",
    "skyridge middle school on top",
  ];
  var randomIndex = Math.floor(Math.random() * greetings.length);
  return greetings[randomIndex];
}

document.getElementById("subtitle").innerText = getRandomGreeting();
